apiVersion: v2
name: kube-prometheus
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 82.2.0
