trivy-operator:
  # Metrics scraping for kube-prometheus-stack
  serviceMonitor:
    enabled: true
    namespace: trivy-system
    labels:
      release: kube-prometheus

  operator:
    # Reduce concurrent scan jobs to limit resource usage
    scanJobsConcurrentLimit: 1
