# From https://artifacthub.io/packages/helm/gitea/gitea
- name: Add Gitea chart repo
  kubernetes.core.helm_repository:
    name: gitea-charts
    repo_url: https://dl.gitea.com/charts

- name: Install Gitea
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_local_path }}"
    name: gitea
    chart_ref: gitea-charts/gitea
    chart_version: 12.4.0
    release_namespace: gitea
    create_namespace: true
    release_values: "{{ lookup('template', './templates/gitea-values.yaml.j2') | from_yaml }}"
    wait: true
    wait_timeout: 10m
