apiVersion: v2
name: argocd
type: application
version: 0.1.0

dependencies:
  # From https://artifacthub.io/packages/helm/traefik/traefik
  - name: traefik
    repository: https://traefik.github.io/charts
    version: 38.0.2
