# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: vault
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "-2"
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/skyf0l/skylab.git
#     targetRevision: main
#     path: k8s/projects/gitops-stack/vault
#     helm:
#       releaseName: vault
#       valueFiles:
#         - values.yaml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: vault
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - Validate=true
#       - PrunePropagationPolicy=foreground
#       - PruneLast=true
#     retry:
#       limit: 5
