apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-injector
  namespace: argocd
spec:
  project: default
  sources:
    # Helm chart from upstream
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.31.0
      helm:
        releaseName: argo
        valueFiles:
          - $values/k8s/src/vault-injector/values.yaml
    # Values from this repo
    - repoURL: https://github.com/skyf0l/skylab.git
      targetRevision: main
      ref: values
    # Extra manifests source
    - repoURL: https://github.com/skyf0l/skylab.git
      targetRevision: main
      path: k8s/src/vault-injector/manifests
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-injector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
